### PR TITLE
Firestore is setup and linked, qr is linked to data. Still working on…

### PR DESCRIPTION
**Pull request by hayes28**
… all of it. Removed the ID since firebase auto generates ids when saving exhibit to firestore. It isn't saving the data I enter into the exhibit form but it is creating an id and storing blank fields to firestore. 
image
I also linked the firestore to the nav button

### CODE REVIEW

**Comment by hayes28** [comment]
image
I had to move state management up to a common parent component, which simplifies the data flow and makes it easier to handle the form submission to Firestore

**Comment by Oggal** [comment]
Should we re-add the exhibit ID field so we can set a human readable ID?
This would be used as our 4 'digit'(alpha-numeric) code to pull up a page without scanning a QR code

**Comment by hayes28** [comment]
Yes I wanted to talk to you about this because I'm at a loss for how to link all of that together. Firestone auto generates a id so maybe I can do some more research on how to customize that. Or maybe there is a way to have the qr code generate a 4 digit code below it as part of the qr that's generated.

**Comment by hayes28** [comment]
Oh also in the ExhibitForm the url for storing to Firestore should be localhost for everyone until we host and have our url. Mine just doesn't work on the localhost so that's my home network url.

**Pull request merged**
